<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6grTRxI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6grTRxI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6grTRxI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6grTRxI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6grTRxI\App_KernelDevDebugContainer([
    'container.build_hash' => '6grTRxI',
    'container.build_id' => '3a012e8f',
    'container.build_time' => 1590861108,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6grTRxI');
