<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'getCompanies' => [[], ['_controller' => 'App\\Controller\\CompanyController::getCompanies'], [], [['text', '/companies']], [], []],
    'getCompany' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\CompanyController::getCompany'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], []],
    'postCompany' => [[], ['_controller' => 'App\\Controller\\CompanyController::createCompany'], [], [['text', '/company']], [], []],
    'updateCompany' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\CompanyController::updateCompany'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], []],
    'deleteCompany' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\CompanyController::deleteCompany'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/company']], [], []],
    'getUsers' => [[], ['_controller' => 'App\\Controller\\UserController::getUsers'], [], [['text', '/users']], [], []],
    'getUser' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\UserController::getUsero'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'postUser' => [[], ['_controller' => 'App\\Controller\\UserController::createUser'], [], [['text', '/users']], [], []],
    'putUser' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\UserController::putUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'deleteUser' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\UserController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'getVacanciesByCompanyId' => [['companyId'], ['companyId' => 1, '_controller' => 'App\\Controller\\VacancyController::getVacancies'], [], [['variable', '/', '[^/]++', 'companyId', true], ['text', '/vacancies']], [], []],
    'getVacancy' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\VacancyController::getVacancy'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/vacancy']], [], []],
    'postVacancy' => [[], ['_controller' => 'App\\Controller\\VacancyController::createVacancy'], [], [['text', '/vacancy']], [], []],
    'patchVacancy' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\VacancyController::updateVacancy'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/vacancy']], [], []],
    'deleteVacancy' => [['id'], ['id' => 1, '_controller' => 'App\\Controller\\VacancyController::deleteVacancy'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/vacancy']], [], []],
];
